sudo: false
language: java
jdk:
- oraclejdk8
- oraclejdk7
deploy:
  provider: script
  script: "./gradlew uploadSdkArtifacts"
  on:
    tags: true
repo: eyedol/voto-java-sdk
script: "./gradlew clean build"
after_success:
- bash <(curl -s https://codecov.io/bash)
- "./deploy_snapshot.sh"
before_cache:
- rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
env:
  global:
  - secure: C0UIVkCuk4gtHW5l7kgXM5aX6z3WeaPWoxS6NAjBLZq/ni9kle//Y+7TDGZRluB/wYTV4u/Fwqrq46CwZmoiNoEoT4KrPbxZFgRwam62S44ahYk1nahOT/IJ8kiX+W5g6JvYbQ2nDJH8WNCSXvmyMFoM/n1OZCLvF7xXQM/GrBokGzeaE11hn5RAlZX3pVseIiqcCZzDR0/HZwQH6obpFmip908AJyoA8rn8XWYw2296/C6fpJdS+OrZxGVqesRd+tyE+LgW4KmIqgT7g0HkmSqckiD8rgg6B2hEUG152LDHXgsBAvwPtaD5YlTAP0lGr5tHjiKnfGHI7mthCbopSNR8fqmH5V9GL3gdxad4oklWrYfF253acElU663vaDOXDXtzgVX4W96QBpXyJpo8xEyVxaMKdGpziJPNSbsYJzAb6rw5j0mvJMMhWW+kqhyp5KpMpyHG28WzfvXQXer3V8QLiin6EVCSGMYM8v1lGEo2yiBtNxAYrqCfO9yu4qJxidjo+Uf1gX+jag7ZPtUdTOlkuKzRtrsPR5Lvkg8Ok4jWZh+jrlXLjh8GWvY8vqr50eEDFe/h40Lwi4UNxJ+IzQvPpULNnMjK29r72BD8eKW5/4VJSEDRTf2V1KYScBPY+VPCv1x5tRtHDr9hcuE7jO+a80aRfQv2/Xtow4iyjb0=
  - secure: OooX4MBeP8ehtDoOjidLrqAQvk3i3ILPDz/Bf4XVq9+A4eKlO4X8/CagRqNXLa189YYrBJcS5YSbDQ8RahF7DFw8HtorDOypruGovyZN8dVX1FzbDvwPSg00TWYM1meHSmDKhd3Vn6pqsYjoH4Xc5/qMT6fhfyH4R4xBih0GlqEnPwoynVPV9ucBVT+jKTM5MUf/qTn8SBgKKTspmP0WQSzlpCqtzDxtTbAOANl3AMSWBGcy6u6KIE2SuiFKcNswARzNvkNjGc8Rq6M1d/uxOxNhNEMbOkTlZgAGylxiEAscI7nu+O3kp1BfSVUj/Uabq+NohySzRdaySgcgDHqAoU1/63IqVx8f4cTin+8Wui/UHF+U1WXeLLehWU1glA4Va1at4lU/S0gRSgFiNKwMhRZsgp/RULrZs36nfR3dled1BSy2EQ6c4o5bYt43u5qRyleNFTqv79eV3qF5tjk/TrZBOW/lF7zyq/W7QoN9aCLzyddnaHkXhc9IxFpKtFpZKtZ1TNEvwxO7Po6MerwELcPKlPJiZ4uuSLk8+wIghv06Mm7JSvpdfnqmWHbpR4ynJn2cOInn2dCliT27OSawmwfr/5O1Aguh2Q+C+HZc2uW+Sc645QWVsDEeSurtrgnE/w2Z3xkfbi6uvoUTlTi9I6dTLqPqDCjj4VwAgP3BmgM=
  - secure: sFqV8Sr6nqEUmbB5IhDUDhmk1oR0rwPmYKJ39EbSKtyA9aYDeCsX4/ClBa2lWeUTdJ+0XkFdTe78HjRqVFS5JfSuS1jb52vcIMBapKLlSW1qUV2JAjq7+A7HRPYcUXKeYvhX3vTnRH72uYfHGP/MgkN5WL3MBwdS4OwiKjj3FtcQaSz6cZxckAe7hGWaitd2gFaILfABcWNB5uQM4ve1MY/8eWxWS6i/KnYhSXlrNN5uiVrmBUz9MMnUdgGG3/XPu06ejMHpnfp9yqNQDDHURjsjV3t4SZ20yCaw/O5b83oim14FHAT+l+kv6NQKwRyzP5um6Pt/TgOZ2n6C6EgFfaZISy6HFrlPYddaK+KmdR24AsLITu2nSbR0vRutA9XLMuo51GhqrZ2/9khEodj0W6q3xGOyEdpkZcOIduLmJo6yHaFDhANcxcKTxsa0XgqNGUO0MJ89gt8YraCetSXvwZW71njk7A2DHc/F7afThIH7WIKEEDaQ1xExmzprou52vLerM5gkzzWHi0azfzIdgIHY/HXYQkbnG7zbaGNAycxTHVXvyyMAxHUhsZWT42wJ1utuGZTD+aUnn7aq4dW0+fmA0eiYVwI8S6jeBOHPbCXA+aJ1hAvuCct2ZcCLx8d9GaV0Ut7Xgmq3B+Wt9pQwjHsHuJkmsSAXVvcWvT8Pl78=
  - secure: nytPukSU2CDFmaXF63tKkGCPOztYHwcPjC4jVfpZN+IEjVVkVZs20GcAI1z7lKgXz2zyNpK0pKkHwMDKoV5bgGKQcfSy4uSgiOqrlobnyKIJESK6tPnDqNqGCQrpGgXUmpD/ia8l4eg5+Iwa+8/7HMXYrJwL6gOXJ6bXu0bOJ5XyEPF6bcUu1ZSz+Y6UnPCktGa9eo6J81vRL4s22gkPgvtOM21IVuP3DHT0MPyAlcrk22JJoxrM7RPdNlwFblrQArQLrwYOZxa+85f3TbWpz0t6/cXHBoLQcuyqy1UI0mfhhNKJSOFlpoYu518w/8Cu0xhIRRRW4bJwn83EqswC5jm1XY57kk+ji+rT33E/B28WNR2phfWf37U3zohqLjjLfEgcxFnFRBi9JdRrmSLR4EJ5/pDbj+z63tSDO7ezmjaAuYjWBHuD2Xou6x33hYtuRR9WzBG2Z7JAMLl8kjFmSeQzF0pTmwudjmWPDnMeaEQiNhp9jnpf6iZWywKriiEJf1AjgCgLLceh5hbWxsh4ts7t54WvjiXbJ7tH6J/Q/MbbTVJ86/oqRnRW/x4VvSzFnHfFjpCJg5zKFoAlBACfZ7WKbubYfVwFVYBu4r9Qalkdx33GHITlwgQm7lIaLgjYNL4ijrPnMVtF8SccO1wk0aRRbCKuuwCmduDecDD5Skw=
