---
sudo: false
language: java
jdk:
  - oraclejdk8
  - oraclejdk7
before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
script: ./gradlew clean build

# Upload code coverage report to codecov
after_success:
  - bash <(curl -s https://codecov.io/bash)